### ISSUE TITLE
vulkan: physical device does not support DRM format modifiers

### ISSUE THREAD

**Issue by ghost** [Frogging-Family/gamescope-git#4]
Hello, I'm trying to run a windows game on Manjaro Linux. The game doesn't like alt-tabbing out and back in again and I was pointed to this project to fix this.
`gamescope -w 1280 -h 720 -- wine 'Factory Town.exe'`
gives me:
```
No CAP_SYS_NICE, falling back to regular-priority compute and threads.
Performance will be affected.
vulkan: selecting physical device 'Quadro K2200'
vulkan: physical device does not support DRM format modifiers
vulkan: vkCreateDevice failed (VkResult: -7)
Failed to initialize Vulkan
```
I have a native linux game that is using Vulkan, Is this fixable or is it simply not going to work with my card?
Many thanks!

**Comment by Riesi** [comment]
Gamescope doesnt work on Nvidia GPUs as of yet. The Nvidia driver is missing some things still to get it supported.

This is stated on the official Gamescope GitHub repository.

Read this section:
https://github.com/Plagman/gamescope#gamescope-the-micro-compositor-formerly-known-as-steamcompmgr
