### ISSUE TITLE
FSR Patch fails

### ISSUE THREAD

**Issue by int-72h** [Frogging-Family/gamescope-git#6]
I seem to get `Hunk #4 FAILED at 247.` in src/main.cpp.
Pulled fresh and the same issue occurs.

**Comment by ghost** [comment]
I rebased the fsr branch repo to include the latest gamescope changes, makepkg with fsr of this repo should work now.

**Comment by IDeathByte** [comment]
works well now for me
You didn't plan push patch to main branch?
